# Generated by Django 3.0.7 on 2020-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('isIndian', models.BooleanField(max_length=200)),
                ('companySummary', models.TextField()),
            ],
        ),
    ]
